export const menuData = {
  categories: [
    {
      id: "entradas",
      name: "Entradas",
      icon: "🥗",
      items: [
        {
          id: "e1",
          name: "Guacamole Tradicional",
          description: "Aguacate fresco, cilantro, cebolla, tomate y limón. Servido con totopos crujientes.",
          price: 8.99,
          image: "/fresh-guacamole-chips.png",
          badges: ["Más Vendido", "Vegano"],
        },
        {
          id: "e2",
          name: "Alitas Picantes",
          description: "Alitas de pollo marinadas en salsa búfalo con aderezo ranch.",
          price: 12.99,
          image: "/spicy-buffalo-chicken-wings.jpg",
          badges: ["Picante"],
        },
        {
          id: "e3",
          name: "Nachos Supremos",
          description: "Totopos cubiertos con queso fundido, frijoles, jalapeños, crema y pico de gallo.",
          price: 10.99,
          image: "/loaded-nachos.png",
          badges: ["Más Vendido"],
        },
      ],
    },
    {
      id: "platos-fuertes",
      name: "Platos Fuertes",
      icon: "🍖",
      items: [
        {
          id: "p1",
          name: "Tacos al Pastor",
          description: "Tres tacos de cerdo marinado con piña, cilantro y cebolla en tortillas de maíz.",
          price: 14.99,
          image: "/tacos-al-pastor-with-pineapple.jpg",
          badges: ["Más Vendido"],
        },
        {
          id: "p2",
          name: "Burrito de Carne Asada",
          description: "Tortilla de harina rellena de carne asada, arroz, frijoles, queso y guacamole.",
          price: 16.99,
          image: "/beef-burrito-wrapped.jpg",
        },
        {
          id: "p3",
          name: "Enchiladas Verdes",
          description: "Tortillas rellenas de pollo bañadas en salsa verde con crema y queso.",
          price: 13.99,
          image: "/green-enchiladas-with-cream.jpg",
          badges: ["Picante"],
        },
        {
          id: "p4",
          name: "Quesadilla de Hongos",
          description: "Tortilla de harina con queso Oaxaca y hongos salteados. Incluye guacamole.",
          price: 11.99,
          image: "/mushroom-quesadilla.jpg",
          badges: ["Vegano", "Nuevo"],
        },
        {
          id: "p5",
          name: "Fajitas Mixtas",
          description: "Pollo y res salteados con pimientos y cebolla. Servido con tortillas.",
          price: 18.99,
          image: "/sizzling-fajitas-platter.jpg",
          badges: ["Más Vendido"],
        },
        {
          id: "p6",
          name: "Mole Poblano",
          description: "Pollo bañado en salsa mole tradicional con arroz y tortillas.",
          price: 15.99,
          image: "/chicken-mole-poblano.jpg",
        },
      ],
    },
    {
      id: "bebidas",
      name: "Bebidas",
      icon: "🍹",
      items: [
        {
          id: "b1",
          name: "Margarita Clásica",
          description: "Tequila, triple sec, jugo de limón y jarabe simple con sal en el borde.",
          price: 9.99,
          image: "/classic-margarita-cocktail.jpg",
          badges: ["Más Vendido"],
        },
        {
          id: "b2",
          name: "Agua de Horchata",
          description: "Bebida refrescante de arroz con canela y vainilla.",
          price: 4.99,
          image: "/horchata-drink-glass.jpg",
          badges: ["Vegano"],
        },
        {
          id: "b3",
          name: "Michelada",
          description: "Cerveza preparada con limón, sal, salsa y especias.",
          price: 7.99,
          image: "/michelada-beer-cocktail.jpg",
        },
        {
          id: "b4",
          name: "Limonada Natural",
          description: "Limonada fresca hecha al momento con menta.",
          price: 3.99,
          image: "/fresh-mint-lemonade.png",
          badges: ["Vegano"],
        },
      ],
    },
    {
      id: "postres",
      name: "Postres",
      icon: "🍰",
      items: [
        {
          id: "d1",
          name: "Churros con Chocolate",
          description: "Churros crujientes espolvoreados con azúcar y canela, servidos con chocolate caliente.",
          price: 6.99,
          image: "/churros-chocolate.png",
          badges: ["Más Vendido"],
        },
        {
          id: "d2",
          name: "Flan Napolitano",
          description: "Flan cremoso de vainilla con caramelo.",
          price: 5.99,
          image: "/caramel-flan-dessert.jpg",
        },
        {
          id: "d3",
          name: "Tres Leches",
          description: "Pastel empapado en tres tipos de leche con crema batida.",
          price: 7.99,
          image: "/placeholder.svg?height=300&width=400",
          badges: ["Nuevo"],
        },
      ],
    },
  ],
}
